# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# Site header
header:
  navbar:
    enable: true
    logo:
      # Logo text
      text: "Sw-Saturn"
    blox: custom-navbar
    fixed_to_top: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: "Â© {year} Sw-Saturn. This work is licensed under {license}"
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: true
